Algoritmo "Imprimindo Número de 1 a 100"
// Disciplina   : Algoritmo e Programação
// Professor   : Arthur Mariano L NETO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/10/2023
Var

contador: Inteiro;

Inicio
contador <- 1

   enquanto contador <= 100 faca
      Escreva(contador)
      contador <- contador + 1
   Fimenquanto
   
Fimalgoritmo