Algoritmo "Soma Numeros pares de 1 a 100"
// Disciplina   : Algoritmo e Programação
// Professor   : Arthur Mariano L NETO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/10/2023
Var
soma, numero: Inteiro

Inicio
 soma <- 0

   Para numero de 2 ate 100 passo 2 faca
      soma <- soma + numero
   FimPara

   Escreva("A soma dos números pares de 1 a 100 é: ", soma)
   
Fimalgoritmo