Algoritmo "Calculo Fatorial"
// Disciplina   : Algoritmo e Programação
// Professor   : Arthur Mariano L NETO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/10/2023
Var

N, fatorial, contador: Inteiro

Inicio
Escreva("Digite um número natural: ")
   Leia(N)

fatorial <- 1

  Para contador de 1 ate N faca
     fatorial <- fatorial * contador
 fimPara

Escreva("O fatorial de ", N, " é: ", fatorial)

Fimalgoritmo