Algoritmo "Par ou Impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2023
Var

numero: inteiro;

Inicio

 escreva("Digite um número? ->")
 leia (numero)

 se numero%2<>0 entao
    Escreva ("O número ", numero, " é impar")
         senao
         Escreva ("O número ", numero, " é par")
fimse



Fimalgoritmo
