Algoritmo "CALCULE POTENCIA"
// Disciplina   : Algoritmo e Programação
// Professor   : Arthur Mariano L NETO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/09/2023
Var
x: real;
y: inteiro;
resultado: real;


Inicio
escreva ("Digite o número base->")
leia (x)

escreva ("Digite o número expoente->")
leia (y)

resultado <- x^y

escreva (" o resultado é ", resultado)


Fimalgoritmo